import Head from 'next/head';
import Navigation from '@/components/organisms/Navigation';
import Banner from '@/components/organisms/Banner';
import Products from '@/components/organisms/Products';
import ShoppingCart from '@/components/molecules/ShoppingCart';
import CartItem from '@/components/atoms/CartItem';
import AboutUs from '@/components/organisms/AboutUs';
import Contact from '@/components/organisms/Contact';
import { Image } from 'react-bootstrap';



export default function Home() {
  return (
    <>
      <Head>
        <title>freshness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet"/>
      </Head>
      <header>
     <Navigation/>
     </header>
    
      <main >
      
        <Banner/>
      </main>
      <section>
      <Image src="/images/oferta.jpg" with={100} height={100}/>
        <Products/>
        <ShoppingCart/>
        <CartItem/>
        <AboutUs/>
      </section>
      <footer>
        <Contact/>
      </footer>
      
    </>
  )
}
