import Head from 'next/head'
import Section from "@/components/organisms/Section";
import CardsList from '@/components/molecules/CardsList';
import ShoppingCart from '@/components/molecules/ShoppingCart';
import CartItem from '@/components/atoms/CartItem';




export default function Home() {
  return (
    <>
      <Head>
        <title>frescura.ar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet"/>
      </Head>
      <main >
        <ShoppingCart/>
        <CartItem/>
      </main>
    </>
  )
}
